// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UWPLockStep.Persistance.Services;

namespace UWPLockStep.Persistance.Migrations
{
    [DbContext(typeof(LockStepContextSql))]
    [Migration("20191015203047_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UWPLockStep.Domain.Entities.Element", b =>
                {
                    b.Property<int>("ElementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ElementId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ElementName")
                        .HasColumnName("ElementName");

                    b.Property<string>("ElementType")
                        .HasColumnName("ElementType");

                    b.Property<string>("ElementUnit")
                        .HasColumnName("ElementUnit");

                    b.HasKey("ElementId");

                    b.ToTable("Elements");
                });

            modelBuilder.Entity("UWPLockStep.Domain.Entities.PolicyBase", b =>
                {
                    b.Property<int>("PolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("PolicyId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<decimal>("Maximum")
                        .HasColumnName("Maximum");

                    b.Property<decimal>("Minimum")
                        .HasColumnName("Minimum");

                    b.Property<string>("PatientType")
                        .HasColumnName("PatientType");

                    b.Property<string>("PolicyBasis")
                        .HasColumnName("PolicyBasis");

                    b.Property<long>("PolicyDuration")
                        .HasColumnName("PolicyDuration");

                    b.Property<string>("WarningLevel")
                        .HasColumnName("WarningLevel");

                    b.HasKey("PolicyId");

                    b.ToTable("PolicyBase");

                    b.HasDiscriminator<string>("Discriminator").HasValue("PolicyBase");
                });

            modelBuilder.Entity("UWPLockStep.Domain.Entities.ElementPolicy", b =>
                {
                    b.HasBaseType("UWPLockStep.Domain.Entities.PolicyBase");

                    b.Property<int?>("ElementId");

                    b.HasIndex("ElementId");

                    b.HasDiscriminator().HasValue("ElementPolicy");
                });

            modelBuilder.Entity("UWPLockStep.Domain.Entities.ElementPolicy", b =>
                {
                    b.HasOne("UWPLockStep.Domain.Entities.Element", "Element")
                        .WithMany("ElementPolicies")
                        .HasForeignKey("ElementId");
                });
#pragma warning restore 612, 618
        }
    }
}
